# Generated by Django 4.2.3 on 2023-07-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sektor nomi')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektorlar',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mahalla nomi ')),
                ('sector', models.ForeignKey(help_text='Mahalla qaysi sektorga tegishli ekanligini tanlang', on_delete=django.db.models.deletion.PROTECT, to='mahalla.sector')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahalalar',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('passport', models.CharField(max_length=20, verbose_name='Passport seriya raqami')),
                ('birthdate', models.DateTimeField(verbose_name='tugulgan sanasi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'ayol')], max_length=255, verbose_name='fuqora jinsi')),
                ('educated', models.CharField(choices=[('middle', "O'rta malumotli"), ('senior', 'oliy malumotli')], max_length=255, verbose_name='fuqora malumoti')),
                ('address', models.TextField(verbose_name='Fuqaro manzili')),
                ('iron_notebook', models.CharField(choices=[('YES', 'ha'), ('no', 'yoq')], max_length=255, verbose_name='temir daftarda bormi')),
                ('abroad', models.CharField(choices=[('YES', 'ha'), ('no', 'yoq')], max_length=255, verbose_name='Temir daftarda bormi')),
                ('disabiltiy', models.CharField(choices=[('YES', 'ha'), ('no', 'yoq')], max_length=20, verbose_name='nogironligi bormi')),
                ('womens_notebook', models.CharField(choices=[('YES', 'ha'), ('no', 'yoq')], max_length=20, verbose_name='Ayollar daftarida bormi')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahalla.neighborhood', verbose_name='mahalani tanlang')),
            ],
            options={
                'verbose_name': 'Fuqora',
                'verbose_name_plural': 'Fuqoralar',
                'ordering': ('id',),
            },
        ),
    ]
